// Code generated by templ - DO NOT EDIT.
// source: base.templ

package layouts

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/livghit/go-htmx/flash"
)

func Base(title string, flashes []flash.Flash) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		children := templ.GetChildren(ctx)
		if children == nil {
			children = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)

		_, err = buf.WriteString("<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if err != nil {
			return err
		}
		_, err = buf.WriteString(templ.EscapeString(title))
		if err != nil {
			return err
		}
		_, err = buf.WriteString("</title><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"/static/js/htmx.min.js\" defer></script><script src=\"https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js\" defer></script><meta name=\"htmx-config\" content='{\"defaultSwapStyle\":\"innerHTML\",\"scrollIntoViewOnBoost\":true}'></head><body class=\"bg-gray-50 text-gray-900 min-h-screen\" hx-boost=\"true\">")
		if err != nil {
			return err
		}

		err = Nav().Render(ctx, buf)
		if err != nil {
			return err
		}

		_, err = buf.WriteString("<div id=\"flash-container\" class=\"fixed top-4 right-4 z-50 space-y-2 w-80\">")
		if err != nil {
			return err
		}

		err = FlashList(flashes).Render(ctx, buf)
		if err != nil {
			return err
		}

		_, err = buf.WriteString("</div><main id=\"main-content\" class=\"container mx-auto px-4 py-8\">")
		if err != nil {
			return err
		}

		err = children.Render(ctx, buf)
		if err != nil {
			return err
		}

		_, err = buf.WriteString("</main></body></html>")
		if err != nil {
			return err
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
