// Code generated by templ - DO NOT EDIT.
// source: flash.templ

package layouts

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/livghit/go-htmx/flash"
)

func flashClass(t flash.Type) string {
	switch t {
	case flash.TypeSuccess:
		return "bg-green-50 text-green-800 border border-green-200"
	case flash.TypeError:
		return "bg-red-50 text-red-800 border border-red-200"
	case flash.TypeWarning:
		return "bg-yellow-50 text-yellow-800 border border-yellow-200"
	default:
		return "bg-blue-50 text-blue-800 border border-blue-200"
	}
}

func FlashList(flashes []flash.Flash) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		children := templ.GetChildren(ctx)
		if children == nil {
			children = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_ = children

		for _, f := range flashes {
			err = flashItem(f).Render(ctx, buf)
			if err != nil {
				return err
			}
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}

func flashItem(f flash.Flash) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		children := templ.GetChildren(ctx)
		if children == nil {
			children = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_ = children

		_, err = buf.WriteString("<div x-data=\"{ show: true }\" x-show=\"show\" x-transition class=\"")
		if err != nil {
			return err
		}
		_, err = buf.WriteString(templ.EscapeString("rounded-lg p-4 shadow-lg text-sm font-medium flex items-start justify-between gap-2 " + flashClass(f.Type)))
		if err != nil {
			return err
		}
		_, err = buf.WriteString("\"><span>")
		if err != nil {
			return err
		}
		_, err = buf.WriteString(templ.EscapeString(f.Message))
		if err != nil {
			return err
		}
		_, err = buf.WriteString("</span><button @click=\"show = false\" class=\"ml-2 text-current opacity-60 hover:opacity-100 flex-shrink-0\">&times;</button></div>")
		if err != nil {
			return err
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
