// Code generated by templ - DO NOT EDIT.
// source: nav.templ

package layouts

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
)

func Nav() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}
		ctx = templ.InitializeContext(ctx)
		children := templ.GetChildren(ctx)
		if children == nil {
			children = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_ = children

		_, err = buf.WriteString("<nav class=\"bg-white border-b border-gray-200 px-4 py-3\"><div class=\"container mx-auto flex items-center justify-between\"><a href=\"/\" class=\"text-xl font-bold text-indigo-600\">go-htmx</a><div class=\"flex items-center gap-4\"><a href=\"/\" class=\"text-sm text-gray-600 hover:text-indigo-600\">Home</a><a href=\"/login\" class=\"text-sm text-gray-600 hover:text-indigo-600\">Login</a><a href=\"/register\" class=\"inline-flex items-center px-3 py-1.5 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700\">Sign up</a></div></div></nav>")
		if err != nil {
			return err
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
