// Code generated by templ - DO NOT EDIT.
// source: login.templ

package pages

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/livghit/go-htmx/flash"
	"github.com/livghit/go-htmx/validation"
	"github.com/livghit/go-htmx/views/layouts"
)

func inputClass(hasError bool) string {
	if hasError {
		return "border-red-400 bg-red-50"
	}
	return "border-gray-300 bg-white"
}

func LoginPage(flashes []flash.Flash, errs validation.Errors) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}

		body := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			_, err = io.WriteString(w, "<div class=\"max-w-md mx-auto mt-8\"><div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-8\"><h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Sign in</h1><form method=\"POST\" action=\"/login\" class=\"space-y-4\" hx-post=\"/login\" hx-swap=\"outerHTML\" hx-target=\"closest form\">")
			if err != nil {
				return
			}

			// username field
			_, err = io.WriteString(w, "<div><label for=\"username\" class=\"block text-sm font-medium text-gray-700 mb-1\">Username</label><input id=\"username\" name=\"username\" type=\"text\" autocomplete=\"username\" class=\"w-full rounded-md border px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ")
			if err != nil {
				return
			}
			_, err = io.WriteString(w, templ.EscapeString(inputClass(errs.Has("username"))))
			if err != nil {
				return
			}
			_, err = io.WriteString(w, "\" placeholder=\"your username\">")
			if err != nil {
				return
			}
			if errs.Has("username") {
				_, err = io.WriteString(w, "<p class=\"mt-1 text-xs text-red-600\">")
				if err != nil {
					return
				}
				_, err = io.WriteString(w, templ.EscapeString(errs.First("username")))
				if err != nil {
					return
				}
				_, err = io.WriteString(w, "</p>")
				if err != nil {
					return
				}
			}
			_, err = io.WriteString(w, "</div>")
			if err != nil {
				return
			}

			// password field
			_, err = io.WriteString(w, "<div><label for=\"password\" class=\"block text-sm font-medium text-gray-700 mb-1\">Password</label><input id=\"password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" class=\"w-full rounded-md border px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ")
			if err != nil {
				return
			}
			_, err = io.WriteString(w, templ.EscapeString(inputClass(errs.Has("password"))))
			if err != nil {
				return
			}
			_, err = io.WriteString(w, "\" placeholder=\"••••••••\">")
			if err != nil {
				return
			}
			if errs.Has("password") {
				_, err = io.WriteString(w, "<p class=\"mt-1 text-xs text-red-600\">")
				if err != nil {
					return
				}
				_, err = io.WriteString(w, templ.EscapeString(errs.First("password")))
				if err != nil {
					return
				}
				_, err = io.WriteString(w, "</p>")
				if err != nil {
					return
				}
			}
			_, err = io.WriteString(w, "</div>")
			if err != nil {
				return
			}

			_, err = io.WriteString(w, "<button type=\"submit\" class=\"w-full py-2.5 px-4 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500\">Sign in</button><p class=\"text-center text-sm text-gray-500\">No account yet? <a href=\"/register\" class=\"text-indigo-600 hover:underline\">Create one</a></p></form></div></div>")
			return
		})

		err = layouts.Base("Sign in", flashes).Render(templ.WithChildren(ctx, body), buf)
		if err != nil {
			return err
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
