// Code generated by templ - DO NOT EDIT.
// source: register.templ

package pages

import (
	"bytes"
	"context"
	"io"

	"github.com/a-h/templ"
	"github.com/livghit/go-htmx/flash"
	"github.com/livghit/go-htmx/validation"
	"github.com/livghit/go-htmx/views/layouts"
)

func RegisterPage(flashes []flash.Flash, errs validation.Errors) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
		buf, isBuf := w.(*bytes.Buffer)
		if !isBuf {
			buf = templ.GetBuffer()
			defer templ.ReleaseBuffer(buf)
		}

		body := templ.ComponentFunc(func(ctx context.Context, w io.Writer) (err error) {
			_, err = io.WriteString(w, "<div class=\"max-w-md mx-auto mt-8\"><div class=\"bg-white rounded-xl shadow-sm border border-gray-200 p-8\"><h1 class=\"text-2xl font-bold text-gray-900 mb-6\">Create account</h1><form method=\"POST\" action=\"/register\" class=\"space-y-4\" hx-post=\"/register\" hx-swap=\"outerHTML\" hx-target=\"closest form\">")
			if err != nil {
				return
			}

			writeField := func(id, name, inputType, label, placeholder, autocomplete string, hasErr bool, errMsg string) error {
				_, err = io.WriteString(w, "<div><label for=\""+id+"\" class=\"block text-sm font-medium text-gray-700 mb-1\">"+label+"</label><input id=\""+id+"\" name=\""+name+"\" type=\""+inputType+"\" autocomplete=\""+autocomplete+"\" class=\"w-full rounded-md border px-3 py-2 text-sm shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 ")
				if err != nil {
					return err
				}
				_, err = io.WriteString(w, templ.EscapeString(inputClass(hasErr)))
				if err != nil {
					return err
				}
				_, err = io.WriteString(w, "\" placeholder=\""+placeholder+"\">")
				if err != nil {
					return err
				}
				if hasErr {
					_, err = io.WriteString(w, "<p class=\"mt-1 text-xs text-red-600\">"+templ.EscapeString(errMsg)+"</p>")
					if err != nil {
						return err
					}
				}
				_, err = io.WriteString(w, "</div>")
				return err
			}

			if err = writeField("username", "username", "text", "Username", "choose a username", "username", errs.Has("username"), errs.First("username")); err != nil {
				return
			}
			if err = writeField("email", "email", "email", "Email", "you@example.com", "email", errs.Has("email"), errs.First("email")); err != nil {
				return
			}
			if err = writeField("password", "password", "password", "Password", "min 8 characters", "new-password", errs.Has("password"), errs.First("password")); err != nil {
				return
			}
			if err = writeField("password_confirmation", "password_confirmation", "password", "Confirm password", "repeat password", "new-password", errs.Has("password_confirmation"), errs.First("password_confirmation")); err != nil {
				return
			}

			_, err = io.WriteString(w, "<button type=\"submit\" class=\"w-full py-2.5 px-4 text-sm font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500\">Create account</button><p class=\"text-center text-sm text-gray-500\">Already have an account? <a href=\"/login\" class=\"text-indigo-600 hover:underline\">Sign in</a></p></form></div></div>")
			return
		})

		err = layouts.Base("Create account", flashes).Render(templ.WithChildren(ctx, body), buf)
		if err != nil {
			return err
		}

		if !isBuf {
			_, err = buf.WriteTo(w)
		}
		return err
	})
}
